#ifndef PROCESS_ERROR_CODES_H
#define PROCESS_ERROR_CODES_H

#define NO_ERROR 0

#define FAILED_TO_PARSE_PARAMETERS 10
#define FAILED_TO_CREATE_DAEMON_PROCESS 11
#define FAILED_TO_CREATE_DAEMON_SESSION 12
#define FAILED_TO_SWITCH_DAEMON_WORKING_DIRECTORY 13
#define FAILED_TO_CREATE_SERVER_SOCKET 14
#define FAILED_TO_SET_SERVER_SOCKET_TO_ALLOW_MULTIPLE_CONNECTIONS 15
#define FAILED_TO_BIND_SERVER 16
#define FAILED_TO_CREATE_TERMINATION_PIPE 17

#endif